version: '3.1'
services:
  tarbus-server:
    restart: always
    build:
      context: .
      dockerfile: .app-config/prod/Dockerfile
    container_name: prod-tarbus-server
    volumes:
      - /home/projects/api.tarbus.pl/static:/opt/static
    networks:
      - tarbus-network
networks:
  tarbus-network:
    external: true